version: '3.8'
services:
   sentinel1: &conf
     container_name: sentinel1
     image:  redis
     command: redis-sentinel /etc/redis/sentinel.conf
     ports: 
       - "26379:26379"
     volumes:
       - type: bind 
         source: ./sentinel1.conf
         target: /etc/redis/sentinel.conf 
     networks:
       - redis-ha_redis

   sentinel2: 
     <<: *conf
     container_name: sentinel2
     ports: 
       - "26380:26379"
     volumes:
       - type:  bind 
         source: ./sentinel2.conf
         target: /etc/redis/sentinel.conf 

   sentinel3: 
     <<: *conf
     container_name: sentinel3
     ports: 
       - "26381:26379"
     volumes:
       - type:  bind 
         source: ./sentinel3.conf
         target: /etc/redis/sentinel.conf 
 

networks:
   redis-ha_redis:
     external: true

configs:
   sentinel1_config:
     file: ./sentinel1.conf
   sentinel2_config:
     file: ./sentinel2.conf
   sentinel3_config:
     file: ./sentinel3.conf

